# Generated by Django 5.1.3 on 2024-11-16 12:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_of_purchase', models.DateField(default=datetime.date.today)),
                ('Item_purchased', models.CharField(max_length=200)),
                ('Quantity_purchased', models.FloatField()),
                ('Unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myapp.supplier')),
            ],
        ),
    ]
