# Generated by Django 5.1.3 on 2024-11-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Admn_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Batch', models.CharField(max_length=50)),
                ('Roll_no', models.IntegerField()),
            ],
        ),
    ]
