# Generated by Django 5.1.3 on 2024-11-18 10:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0005_remove_purchase_supplier_delete_student_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Admn_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Batch', models.CharField(max_length=50)),
                ('Roll_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=50, unique=True)),
                ('Address', models.TextField()),
                ('Contact_no', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_of_purchase', models.DateField(default=datetime.date.today)),
                ('Item_purchased', models.CharField(max_length=200)),
                ('Quantity_purchased', models.FloatField()),
                ('Unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myapp.supplier')),
            ],
        ),
    ]
