# Generated by Django 5.1.3 on 2024-11-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
