# Generated by Django 5.1.3 on 2024-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
