# Generated by Django 5.1.3 on 2024-12-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('organic', 'Organic'), ('inorganic', 'Inorganic'), ('furniture', 'Furniture'), ('equipment', 'Equipment'), ('glassware', 'Glassware')], max_length=50)),
                ('specification', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('fund_type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('working', 'Working'), ('damage', 'Damage'), ('repair', 'Repair')], default='working', max_length=50)),
            ],
        ),
    ]
