# Generated by Django 5.1.3 on 2024-12-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
