# Generated by Django 5.1.3 on 2024-12-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_item_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
