# Generated by Django 5.1.3 on 2024-12-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('fund_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('working', 'Working'), ('repair', 'Repair'), ('damaged', 'Damaged')], default='working', max_length=10)),
            ],
        ),
    ]
