# Generated by Django 5.1.3 on 2024-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('organic', 'Organic'), ('inorganic', 'Inorganic'), ('glassware', 'Glassware'), ('equipment', 'Equipment'), ('furniture', 'Furniture')], default='equipment', max_length=20),
        ),
    ]
