# Generated by Django 5.1.3 on 2024-12-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=20)),
            ],
        ),
    ]
