# Generated by Django 5.1.3 on 2024-12-10 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('usageid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('batch', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
            ],
        ),
    ]
