# Generated by Django 5.1.3 on 2024-12-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_usage_date_purchasemain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseMain',
        ),
    ]
