# Generated by Django 5.1.3 on 2024-12-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_purchasemain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
