# Generated by Django 5.1.3 on 2024-12-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMain',
            fields=[
                ('purchase_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
        ),
    ]
