# Generated by Django 5.1.3 on 2024-12-10 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_purchasemain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemain',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
